# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
 - covr

r_github_packages:
  - jimhester/lintr

before_install:
  - Rscript -e 'install.packages(c("devtools","testthat"),repos="http://cran.us.r-project.org")'
  - Rscript -e 'devtools::install_github("RTMC/tmc-r-tester/tmcRtestrunner")'
  - cd tmcrstudioaddin

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package()'
